// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TraceabilitySystem.Infrastructure.Persistence;

#nullable disable

namespace TraceabilitySystem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260625073030_AddTypeAndRemarkToIssueTransactions")]
    partial class AddTypeAndRemarkToIssueTransactions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TraceabilitySystem.Domain.Entities.AppConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("key");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_app_configs");

                    b.ToTable("app_configs");
                });

            modelBuilder.Entity("TraceabilitySystem.Domain.Entities.Issue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("number");

                    b.Property<int>("StockInId")
                        .HasColumnType("int")
                        .HasColumnName("stock_in_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_issues");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ix_issues_number");

                    b.HasIndex("StockInId")
                        .HasDatabaseName("ix_issues_stock_in_id");

                    b.ToTable("issues", (string)null);
                });

            modelBuilder.Entity("TraceabilitySystem.Domain.Entities.IssueTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("IssueId")
                        .HasColumnType("int")
                        .HasColumnName("issue_id");

                    b.Property<decimal>("QtyAfter")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("qty_after");

                    b.Property<decimal>("QtyBefore")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("qty_before");

                    b.Property<decimal>("QtyChange")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("qty_change");

                    b.Property<string>("Remark")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("remark");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_issue_transactions");

                    b.HasIndex("IssueId")
                        .HasDatabaseName("ix_issue_transactions_issue_id");

                    b.ToTable("issue_transactions", (string)null);
                });

            modelBuilder.Entity("TraceabilitySystem.Domain.Entities.MqttPrintRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("longtext")
                        .HasColumnName("error_message");

                    b.Property<string>("IssueNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("issue_number");

                    b.Property<string>("ProcessCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("process_code");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("processed_at");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("raw_payload");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_mqtt_print_requests");

                    b.ToTable("mqtt_print_requests");
                });

            modelBuilder.Entity("TraceabilitySystem.Domain.Entities.Parameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("data_type");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_parameters");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_parameters_code");

                    b.ToTable("parameters");
                });

            modelBuilder.Entity("TraceabilitySystem.Domain.Entities.Part", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("number");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_parts");

                    b.ToTable("parts");
                });

            modelBuilder.Entity("TraceabilitySystem.Domain.Entities.Printer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("Port")
                        .HasColumnType("int")
                        .HasColumnName("port");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_printers");

                    b.ToTable("printers", (string)null);
                });

            modelBuilder.Entity("TraceabilitySystem.Domain.Entities.Process", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_processes");

                    b.ToTable("processes");
                });

            modelBuilder.Entity("TraceabilitySystem.Domain.Entities.ProcessLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("IssueNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("issue_no");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_process_logs");

                    b.ToTable("process_logs");
                });

            modelBuilder.Entity("TraceabilitySystem.Domain.Entities.ProcessLogDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("ParameterId")
                        .HasColumnType("int")
                        .HasColumnName("parameter_id");

                    b.Property<int>("ProcessId")
                        .HasColumnType("int")
                        .HasColumnName("process_id");

                    b.Property<long>("ProcessLogId")
                        .HasColumnType("bigint")
                        .HasColumnName("process_log_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<bool?>("ValueBoolean")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("value_boolean");

                    b.Property<decimal?>("ValueNumber")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("value_number");

                    b.Property<string>("ValueText")
                        .HasColumnType("longtext")
                        .HasColumnName("value_text");

                    b.HasKey("Id")
                        .HasName("pk_process_log_details");

                    b.HasIndex("ParameterId")
                        .HasDatabaseName("ix_process_log_details_parameter_id");

                    b.HasIndex("ProcessId")
                        .HasDatabaseName("ix_process_log_details_process_id");

                    b.HasIndex("ProcessLogId", "ProcessId", "ParameterId")
                        .HasDatabaseName("idx_process_parameter");

                    b.ToTable("process_log_details");
                });

            modelBuilder.Entity("TraceabilitySystem.Domain.Entities.ProcessParameter", b =>
                {
                    b.Property<int>("ProcessId")
                        .HasColumnType("int")
                        .HasColumnName("process_id");

                    b.Property<int>("ParameterId")
                        .HasColumnType("int")
                        .HasColumnName("parameter_id");

                    b.HasKey("ProcessId", "ParameterId")
                        .HasName("pk_process_parameters");

                    b.HasIndex("ParameterId")
                        .HasDatabaseName("ix_process_parameters_parameter_id");

                    b.ToTable("process_parameters");
                });

            modelBuilder.Entity("TraceabilitySystem.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_revoked");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens");
                });

            modelBuilder.Entity("TraceabilitySystem.Domain.Entities.SerialNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("created_by");

                    b.Property<int>("ProcessId")
                        .HasColumnType("int")
                        .HasColumnName("process_id");

                    b.Property<string>("SerialNumberCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("serial_number_code");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_serial_numbers");

                    b.HasIndex("ProcessId")
                        .HasDatabaseName("ix_serial_numbers_process_id");

                    b.HasIndex("SerialNumberCode")
                        .IsUnique()
                        .HasDatabaseName("ix_serial_numbers_serial_number_code");

                    b.ToTable("serial_numbers", (string)null);
                });

            modelBuilder.Entity("TraceabilitySystem.Domain.Entities.SerialNumberIssue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("created_by");

                    b.Property<int>("IssueId")
                        .HasColumnType("int")
                        .HasColumnName("issue_id");

                    b.Property<int>("SerialNumberId")
                        .HasColumnType("int")
                        .HasColumnName("serial_number_id");

                    b.HasKey("Id")
                        .HasName("pk_serial_number_issues");

                    b.HasIndex("IssueId")
                        .HasDatabaseName("ix_serial_number_issues_issue_id");

                    b.HasIndex("SerialNumberId", "IssueId")
                        .IsUnique()
                        .HasDatabaseName("ix_serial_number_issues_serial_number_id_issue_id");

                    b.ToTable("serial_number_issues", (string)null);
                });

            modelBuilder.Entity("TraceabilitySystem.Domain.Entities.SerialNumberRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChildSerialNumberId")
                        .HasColumnType("int")
                        .HasColumnName("child_serial_number_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("created_by");

                    b.Property<int>("ParentSerialNumberId")
                        .HasColumnType("int")
                        .HasColumnName("parent_serial_number_id");

                    b.HasKey("Id")
                        .HasName("pk_serial_number_relations");

                    b.HasIndex("ChildSerialNumberId")
                        .HasDatabaseName("ix_serial_number_relations_child_serial_number_id");

                    b.HasIndex("ParentSerialNumberId", "ChildSerialNumberId")
                        .IsUnique()
                        .HasDatabaseName("ix_serial_number_relations_parent_serial_number_id_child_serial~");

                    b.ToTable("serial_number_relations", (string)null);
                });

            modelBuilder.Entity("TraceabilitySystem.Domain.Entities.StockIn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("PartId")
                        .HasColumnType("int")
                        .HasColumnName("part_id");

                    b.Property<DateTime>("ReceiptDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("receipt_date");

                    b.Property<int>("ReceiptQty")
                        .HasColumnType("int")
                        .HasColumnName("receipt_qty");

                    b.Property<DateTime>("SupplyDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("supply_date");

                    b.Property<int>("SupplyQty")
                        .HasColumnType("int")
                        .HasColumnName("supply_qty");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_stock_ins");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_stock_ins_code");

                    b.HasIndex("PartId")
                        .HasDatabaseName("ix_stock_ins_part_id");

                    b.ToTable("stock_ins", (string)null);
                });

            modelBuilder.Entity("TraceabilitySystem.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users");
                });

            modelBuilder.Entity("TraceabilitySystem.Domain.Entities.Issue", b =>
                {
                    b.HasOne("TraceabilitySystem.Domain.Entities.StockIn", "StockIn")
                        .WithMany("Issues")
                        .HasForeignKey("StockInId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issues_stock_ins_stock_in_id");

                    b.Navigation("StockIn");
                });

            modelBuilder.Entity("TraceabilitySystem.Domain.Entities.IssueTransaction", b =>
                {
                    b.HasOne("TraceabilitySystem.Domain.Entities.Issue", "Issue")
                        .WithMany("Transactions")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_issue_transactions_issues_issue_id");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("TraceabilitySystem.Domain.Entities.ProcessLogDetail", b =>
                {
                    b.HasOne("TraceabilitySystem.Domain.Entities.Parameter", "Parameter")
                        .WithMany()
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_process_log_details_parameters_parameter_id");

                    b.HasOne("TraceabilitySystem.Domain.Entities.Process", "Process")
                        .WithMany()
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_process_log_details_processes_process_id");

                    b.HasOne("TraceabilitySystem.Domain.Entities.ProcessLog", "ProcessLog")
                        .WithMany("Details")
                        .HasForeignKey("ProcessLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_process_log_details_process_logs_process_log_id");

                    b.Navigation("Parameter");

                    b.Navigation("Process");

                    b.Navigation("ProcessLog");
                });

            modelBuilder.Entity("TraceabilitySystem.Domain.Entities.ProcessParameter", b =>
                {
                    b.HasOne("TraceabilitySystem.Domain.Entities.Parameter", "Parameter")
                        .WithMany("ProcessParameters")
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_process_parameters_parameters_parameter_id");

                    b.HasOne("TraceabilitySystem.Domain.Entities.Process", "Process")
                        .WithMany("ProcessParameters")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_process_parameters_processes_process_id");

                    b.Navigation("Parameter");

                    b.Navigation("Process");
                });

            modelBuilder.Entity("TraceabilitySystem.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("TraceabilitySystem.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TraceabilitySystem.Domain.Entities.SerialNumber", b =>
                {
                    b.HasOne("TraceabilitySystem.Domain.Entities.Process", "Process")
                        .WithMany("SerialNumbers")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_serial_numbers_processes_process_id");

                    b.Navigation("Process");
                });

            modelBuilder.Entity("TraceabilitySystem.Domain.Entities.SerialNumberIssue", b =>
                {
                    b.HasOne("TraceabilitySystem.Domain.Entities.Issue", "Issue")
                        .WithMany("SerialNumberIssues")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_serial_number_issues_issues_issue_id");

                    b.HasOne("TraceabilitySystem.Domain.Entities.SerialNumber", "SerialNumber")
                        .WithMany("Issues")
                        .HasForeignKey("SerialNumberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_serial_number_issues_serial_numbers_serial_number_id");

                    b.Navigation("Issue");

                    b.Navigation("SerialNumber");
                });

            modelBuilder.Entity("TraceabilitySystem.Domain.Entities.SerialNumberRelation", b =>
                {
                    b.HasOne("TraceabilitySystem.Domain.Entities.SerialNumber", "ChildSerialNumber")
                        .WithMany("ChildRelations")
                        .HasForeignKey("ChildSerialNumberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_serial_number_relations_serial_numbers_child_serial_number_id");

                    b.HasOne("TraceabilitySystem.Domain.Entities.SerialNumber", "ParentSerialNumber")
                        .WithMany("ParentRelations")
                        .HasForeignKey("ParentSerialNumberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_serial_number_relations_serial_numbers_parent_serial_number_~");

                    b.Navigation("ChildSerialNumber");

                    b.Navigation("ParentSerialNumber");
                });

            modelBuilder.Entity("TraceabilitySystem.Domain.Entities.StockIn", b =>
                {
                    b.HasOne("TraceabilitySystem.Domain.Entities.Part", "Part")
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_ins_parts_part_id");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("TraceabilitySystem.Domain.Entities.Issue", b =>
                {
                    b.Navigation("SerialNumberIssues");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("TraceabilitySystem.Domain.Entities.Parameter", b =>
                {
                    b.Navigation("ProcessParameters");
                });

            modelBuilder.Entity("TraceabilitySystem.Domain.Entities.Process", b =>
                {
                    b.Navigation("ProcessParameters");

                    b.Navigation("SerialNumbers");
                });

            modelBuilder.Entity("TraceabilitySystem.Domain.Entities.ProcessLog", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("TraceabilitySystem.Domain.Entities.SerialNumber", b =>
                {
                    b.Navigation("ChildRelations");

                    b.Navigation("Issues");

                    b.Navigation("ParentRelations");
                });

            modelBuilder.Entity("TraceabilitySystem.Domain.Entities.StockIn", b =>
                {
                    b.Navigation("Issues");
                });

            modelBuilder.Entity("TraceabilitySystem.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
