<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\TraceabilitySystem.Domain\TraceabilitySystem.Domain.csproj" />
    <ProjectReference Include="..\TraceabilitySystem.Shared\TraceabilitySystem.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Mapster" Version="10.0.7" />
    <PackageReference Include="EPPlus" Version="7.4.2" />
    <PackageReference Include="System.Management" Version="10.0.10" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
